name: Release Candidate Builder
on: 
  push:
    branches:
      - "!*"
    tags:
      - "!*RC*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build and test
        run: mvn clean install